services:
  reverse-proxy:
    image: traefik:v3.1.0
    command:
    - "--api.insecure=false"
    - "--api.dashboard=true"
    - "--providers.docker"
    - "--providers.docker.exposedByDefault=false"
    - "--providers.docker.network=proxynet"
    - "--log.level=DEBUG"
    # Entrypoints:
    - "--entrypoints.http.address=:80"
    - "--entrypoints.mysql.address=:3306"
    - "--entrypoints.http.http.redirections.entrypoint.to=https"
    - "--entrypoints.http.http.redirections.entrypoint.scheme=https"
    - "--entrypoints.https.address=:443"
    # Let's Encrypt
    - "--entrypoints.https.http.tls.certResolver=le"
    - "--certificatesresolvers.le.acme.tlschallenge=true"
    - "--certificatesresolvers.le.acme.email=utyaganovnik@yandex.ru"
    - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.dashboard.rule=Host(`traefik.demo.wireflex.online`)"
     - "traefik.http.routers.dashboard.entrypoints=https"
     - "traefik.http.routers.dashboard.service=api@internal"
     - "traefik.http.routers.dashboard.middlewares=auth"
     - "traefik.http.middlewares.auth.basicauth.users=wireflex:$$apr1$$EbJL18XP$$lUKElP3HMrSBKlo7qHNCU/"
    ports:
      - "80:80"
      - "443:443"
      - "3306:3306"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/letsencrypt:/letsencrypt

  apache:
    image: httpd:latest
    container_name: apache
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.apache.rule=Host(`apache.demo.wireflex.online`)"
    depends_on:
      - reverse-proxy

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.grafana.rule=Host(`grafana.demo.wireflex.online`)"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    depends_on:
      - apache

  mysql:
    image: mariadb:latest
    restart: always
    container_name: mariadb
    environment:
      - MYSQL_DATABASE=mysqldb
      - MYSQL_USER=userdb
      - MYSQL_PASSWORD=passdb
      - MYSQL_ROOT_PASSWORD=rootpassdb
    labels:
        - "traefik.enable=true"
        - "traefik.tcp.routers.mysql.rule=HostSNI(`*`)"
        - "traefik.tcp.routers.mysql.entrypoints=mysql"
        - "traefik.tcp.routers.mysql.service=mysql-svc"
        - "traefik.tcp.services.mysql-svc.loadbalancer.server.port=3306"
    depends_on:
      - grafana

  nginx:
    image: nginx:latest
    container_name: nginx
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nginx.rule=Host(`nginx.demo.wireflex.online`)"
    depends_on:
      - mysql

  whoami:
    image: traefik/whoami
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`whoami.demo.wireflex.online`)"
    depends_on:
      - nginx

networks:
  default:
    name: proxynet
    external: true
