  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.grafana.rule=Host(`grafana.demo.wireflex.online`)"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"
