  whoami:
    image: traefik/whoami
    # вырубаем имя контейнера для будущего scale ( docker compose -f whoami-compose.yml up -d --scale whoami=2 ) будет работать loadbalancer
    # container_name: whoami
    labels:
        # включение traefik для grafana
        - "traefik.enable=true"
        # на этот контейнер будут перенаправляться запросы, которые приходят на whoami.demo
        - "traefik.http.routers.whoami.rule=Host(`whoami.demo.wireflex.online`)"
